export const GLOBAL_CATALOG = [
  { title: "Alvejante Sem Cloro FAZ", price: "R$ 58,12", sub: "Caixa 4x5L", tag: "Lavanderia", color: "#ec4899" },
  { title: "Amaciante de Roupas BLUE", price: "R$ 46,33", sub: "Caixa 4x5L", tag: "Lavanderia", color: "#38bdf8" },
  { title: "Lava Roupas Liq. Floral FAZ", price: "R$ 74,87", sub: "Caixa 4x5L", tag: "Lavanderia", color: "#0ea5e9" },
  { title: "Lava Roupas Liq. Coco FAZ", price: "R$ 74,87", sub: "Caixa 4x5L", tag: "Lavanderia", color: "#fed7aa" },
  { title: "Desinfetante Lavanda FAZ", price: "R$ 34,51", sub: "Caixa 4x5L", tag: "Banheiro", color: "#a855f7" },
  { title: "Desinfetante Pinho FAZ", price: "R$ 34,51", sub: "Caixa 4x5L", tag: "Banheiro", color: "#16a34a" },
  { title: "Desinfetante Citronela FAZ", price: "R$ 34,51", sub: "Caixa 4x5L", tag: "Banheiro", color: "#06b6d4" },
  { title: "Detergente Amoniacal DA50", price: "R$ 51,22", sub: "Caixa 4x5L", tag: "Limpeza Pesada", color: "#22c55e" },
  { title: "Detergente Neutro FAZ", price: "R$ 52,76", sub: "Caixa 4x5L", tag: "Cozinha", color: "#fef08a" },
  { title: "Desengordurante Fazmol", price: "R$ 97,36", sub: "Caixa 4x5L", tag: "Cozinha", color: "#a3e635" },
  { title: "Limpa Forno FAZ", price: "R$ 54,70", sub: "Caixa 4x5L", tag: "Limpeza Pesada", color: "#166534" },
  { title: "Limpa Pedra Fazclean", price: "R$ 72,18", sub: "Caixa 4x5L", tag: "Limpeza Pesada", color: "#6366f1" },
  { title: "Multiuso Floral FAZ", price: "R$ 45,72", sub: "Caixa 4x5L", tag: "Limpeza Geral", color: "#f472b6" },
  { title: "Álcool Perfumado Floral", price: "R$ 60,00", sub: "Caixa 4x5L", tag: "Limpeza Geral", color: "#f472b6" },
  { title: "Água Sanitária FAZ", price: "R$ 28,00", sub: "Caixa 4x5L", tag: "Limpeza Geral", color: "#115e59" },
  { title: "Soda Cáustica Escama 99%", price: "R$ 221,35", sub: "Caixa 12x1Kg", tag: "Especiais", color: "#ffffff" },
  { title: "Álcool em Gel Fortmaster", price: "R$ 144,67", sub: "Caixa 12x1L", tag: "Fortmaster", color: "#e2e8f0" },
  { title: "Sabonete Líq. Açaí & Pitanga", price: "R$ 145,60", sub: "Cx Pump 12x1L", tag: "Fortmaster", color: "#c026d3" },
  { title: "Sabonete Líq. Erva Doce", price: "R$ 145,60", sub: "Cx Pump 12x1L", tag: "Fortmaster", color: "#4ade80" },
  { title: "Sabonete Líq. Algas", price: "R$ 145,60", sub: "Cx Pump 12x1L", tag: "Fortmaster", color: "#0284c7" },
];
